theme: jekyll-theme-minimal
title: ePortfolio 2026 - Bond
description: "Hello, my name is Adia Bond, and this is an ePortfolio showcasing my 2026 capstone."
url: "https://bond7736.github.io"
baseurl: ""
